<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/11/18 18:48:45
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
