<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/09 09:04:17
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
