<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/02 00:03:03
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
